# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  graphql-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: graphql-mysql
    volumes:
      - graphql-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=graphql
      - MYSQL_DATABASE=graphql
      - MYSQL_USER=graphql
      - MYSQL_PASSWORD=graphql
  # PHP (with Nginx)
  # app:
  #   image: ambientum/php:7.2-nginx
  #   container_name: graphql-app
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .:/var/www/app
  #   ports:
  #     - "80:8080"
  #   links:
  #     - mysql
  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: graphql-phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "81:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=graphql
      - MYSQL_USER=graphql
      - MYSQL_PASSWORD=graphql
